---
- name: creating a foleder
  file:
   path: /opt/tomcat
   state: directory
   mode: '0755'


- name: i want to extract tar file
  command:
   cmd: sudo tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
   creates: /otp/tomcat/license
   src: /home/ubuntu/apache-tomcat-8.5.5.tar.gz
   dest: /opt/tomcat/
   extra_opts: [--strip-components=1]
  remote_src: yes
  