---
# tasks file for mytom8onU16
- include: myjavainstall.yml
- include: tomusergrp.yml
- include: installtom.yml
- include: extdir.yml
- include: changpermissions.yml
- include: tomconfig.yml
- include: demonstart.yml
- include: tomcatusers.yml
- include: tomcatmanager.yml
- include: tomrestart.yml
- include: jenkins.yml
- include: tomrestart.yml
