--- 
 - name: copy the manager xml file into node
   template:
    src: template/tommanager.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml
 - name: copy the host manager xml file in to node
   template:
     src: template/hostmanager.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
     